"""Build the machine-readable download manifest.

One JSON document describing every source, every concrete target URL, and how
to fetch it. It is the contract shared by two consumers that otherwise know
nothing about each other:

  - the static site (`public/index.html`) renders it as the download index,
  - the Cloudflare Worker resolves `/api/download/<key>` redirects from it.

Generated by `astro manifest`; the copy under `public/` is committed so the
Cloudflare build (which only runs `uv sync` and `npx wrangler deploy`) has it
available without a generation step.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .core.config import settings
from .downloaders import DOWNLOAD_PLAN, unfetchable_reason
from .sources.links import LINKS, DownloadTarget
from .sources.registry import SOURCES

MANIFEST_VERSION = 1


def _target_entry(target: DownloadTarget) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "filename": target.filename,
        "url": target.resolved_url,
        "method": target.method,
        "media_type": target.media_type,
        "timeout_seconds": target.timeout,
        "browser_fetchable": target.browser_fetchable,
        "curl": target.curl_command(),
    }
    if target.data:
        entry["form_data"] = dict(target.data)
    if target.headers:
        # Never publish header *values* — an Authorization bearer token would
        # end up in a public JSON file. Names only; the curl snippet shows a
        # placeholder for the same reason.
        entry["required_headers"] = sorted(target.headers)
    if target.approx_bytes is not None:
        entry["approx_bytes"] = target.approx_bytes
    if target.note:
        entry["note"] = target.note
    return entry


def _source_entry(key: str) -> dict[str, Any]:
    spec = SOURCES[key]
    links = LINKS[key]
    targets = [_target_entry(t) for t in links.targets]
    entry: dict[str, Any] = {
        "key": key,
        "name": spec.name,
        "tier": spec.tier,
        "category": spec.category,
        "license": spec.license,
        "status": links.status.value,
        "fetchable": DOWNLOAD_PLAN.get(key) is not None,
        "landing_page": links.landing_page or spec.base_url,
        "target_count": len(targets),
        "targets": targets,
    }
    reason = unfetchable_reason(key)
    if reason:
        entry["unfetchable_reason"] = reason
    if links.credential_env:
        entry["credential_env"] = list(links.credential_env)
    if links.replaced_by:
        entry["replaced_by"] = links.replaced_by
    notes = " ".join(n for n in (links.note, spec.notes) if n)
    if notes:
        entry["notes"] = notes
    total = sum(t.approx_bytes or 0 for t in links.targets)
    if total:
        entry["approx_bytes"] = total
    return entry


def build_manifest() -> dict[str, Any]:
    sources = [_source_entry(key) for key in sorted(LINKS)]
    by_tier: dict[str, int] = {}
    for source in sources:
        bucket = f"tier{source['tier']}"
        by_tier[bucket] = by_tier.get(bucket, 0) + 1
    return {
        "manifest_version": MANIFEST_VERSION,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "project": "astro-datalake",
        "counts": {
            "sources": len(sources),
            "targets": sum(s["target_count"] for s in sources),
            "fetchable_sources": sum(1 for s in sources if s["fetchable"]),
            "by_tier": dict(sorted(by_tier.items())),
        },
        "sources": sources,
    }


def default_manifest_path() -> Path:
    return settings.project_root / "public" / "manifest.json"


def render_manifest(manifest: dict[str, Any] | None = None) -> str:
    return json.dumps(manifest or build_manifest(), indent=2, sort_keys=False) + "\n"


def write_manifest(path: Path | None = None) -> Path:
    target = path or default_manifest_path()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render_manifest())
    return target


def manifest_is_current(path: Path | None = None) -> bool:
    """True if the on-disk manifest matches what build_manifest() produces now.

    `generated_at` is excluded from the comparison — a timestamp differing is
    not drift, a changed link is.
    """
    target = path or default_manifest_path()
    if not target.exists():
        return False
    try:
        on_disk = json.loads(target.read_text())
    except json.JSONDecodeError:
        return False
    fresh = build_manifest()
    on_disk.pop("generated_at", None)
    fresh.pop("generated_at", None)
    return on_disk == fresh
